[package]
name = "serpapi"
version = "1.1.0"
edition = "2021"
description = "Integrate search data into your rust application. This library is the official wrapper for SerpApi. SerpApi supports Google, Google Maps, Google Shopping, Baidu, Yandex, Yahoo, eBay, App Stores, and more."
readme = "README.md"
homepage = "https://serpapi.com"
documentation = "https://serpapi.com/search-api"
repository = "https://github.com/serpapi/serpapi-rust"
license = "MIT"
authors = ["Victor Benarbia <victor@serpapi.com>"]
keywords = ["google", "search", "engine", "scrape", "ai"]
categories = ["network-programming", "parsing", "web-programming::http-client", "api-bindings"]

include = [
  "Cargo.toml",
  "LICENSE",
  "src/**/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# json parser
serde_json = "1.0"
# Asynchronous runtime
tokio = { version = "1", features = ["full"] }
# HTTP client
reqwest = "0.11.7"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
memory-stats = "1.0"
futures = "0.3"

[[bench]]
name = "search_query"
harness = false
